name: Hello World with CODEOWNERS

# Run on both pushes and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.app-id }}
          private-key: ${{ secrets.app-private-key }}
          owner: ${{ github.repository_owner }}

      - name: Check Codeowners Approval
        uses: noamelf/codeowner-multi-approval-action@main
        with:
          pr-number: ${{ github.event.pull_request.number }}
          repo-name: ${{ github.repository }}
          github-token: ${{ steps.app-token.outputs.token }}
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from a workflow that runs on pushes and pull requests!"

      - name: Display CODEOWNERS file
        run: |
          echo "---- CONTENTS OF CODEOWNERS ----"
          cat CODEOWNERS


