name: Hello World with CODEOWNERS

# Run on both pushes and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Check Codeowners Approval
        uses: aflat-org/codeowner-multi-approval-action@main
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          SOME_OTHER_SECRET: ${{ secrets.SOME_OTHER_SECRET }}
        with:
          pr-number: ${{ github.event.pull_request.number }}
          repo-name: ${{ github.repository }}
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from a workflow that runs on pushes and pull requests!"

      - name: Display CODEOWNERS file
        run: |
          echo "---- CONTENTS OF CODEOWNERS ----"
          cat CODEOWNERS


